@startuml Bank

class Bank {
  - accounts : vector<Account>
  - liquidity : int

  + createAccount()
  + deleteAccount()
  + deposit()
  + giveLoan()
}

class Account {
  - id : int
  - balance : int
  - loan : int

  + getId() const
  + getBalance() const
}

Bank "1" --> "*" Account

@enduml

'alt+D pour activer le visuel